# Generated by Django 5.0.7 on 2024-08-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
